spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: 123456
    url: jdbc:h2:file:~/.myblog/db

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    cache: false